# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  name: Azure Pipelines
  vmImage: 'windows-2022'
  demands:
  - msbuild
  - visualstudio

variables:
  Solution: '**/*.sln'
  Platform: 'x64'
  Runtime: 'win-x64'
  Configuration: 'Publish'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/SysBot.Pokemon.WinForms/SysBot.Pokemon.WinForms.csproj'
    zipAfterPublish: true
    arguments: -p:PublishProfile=FolderProfile -c $(Configuration) -r $(Runtime)
    feedsToUse: 'select'
    includeNuGetOrg: true
    versioningScheme: 'off'
    

- task: PublishPipelineArtifact@0
  displayName: 'Publish Artifact: SysSwapBot-x64'
  inputs:
    targetPath: '**/SysBot.Pokemon.WinForms/bin/x64/Publish/net7.0-windows/win-x64/publish/*.zip'
    artifactName: SysSwapBot-x64
  condition: succeededOrFailed()
